#!/bin/bash
#
# Check the correct # of arguments
#
if [ $# -lt 3 ]; then
	printf "%b" "Error. Not enough arguments.\n" >&2
	printf "%b" "usage: myscript file1 op file2\n" >&2
	exit 1
elif [ $# -gt 3 ]; then
	printf "%b" "Error. To many arguments.\n" >&2
	printf "%b" "usage: myscript file1 op file2\n" >&2
	exit 2
else
	printf "%b" "Argument count correct. Proceeding...\n"
fi

