#!/bin/bash

echo this   was           very  widely         spaced
echo "this   was           very  widely         spaced"
echo 'this   was           very  widely         spaced'

echo -n prompt
echo ''
echo -e 'hi\c'

echo fill it up > file.txt

echo some more data > ../examples/echo.out
