#!/bin/bash

cd ..
SCRIPTS_DIR=$(pwd)/*
echo "Directory: $SCRIPTS_DIR"

for SCRIPT in $SCRIPTS_DIR
do
	if [ -f "$SCRIPT" -a -x "$SCRIPT" ]; then
		echo "Executing '$SCRIPT' script..."
		$SCRIPT
	fi
done

